### ISSUE TITLE
Error viewing resources logges in as a manager

### ISSUE THREAD

**Issue by Phillarby** [chiefonboarding/ChiefOnboarding#253]
A manager has assigned tasks assigned, receives and email and logs in.  When clicking on the 'ToDo' items tab the following is received:

![2022-12-01_10-57-41](https://user-images.githubusercontent.com/855880/205036127-ad99e3dd-d8e3-49a6-adbb-e23166381c7e.jpg)

Traceback:
Environment:

Request Method: GET
Request URL: http://localhost:8000/new_hire/todos/

Django Version: 3.2.15
Python Version: 3.9.15
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'users',
 'organization',
 'user_auth',
 'misc',
 'back',
 'admin.templates',
 'admin.notes',
 'admin.to_do',
 'admin.resources',
 'admin.introductions',
 'admin.admin_tasks',
 'admin.badges',
 'admin.integrations',
 'admin.preboarding',
 'admin.appointments',
 'admin.sequences',
 'admin.people',
 'admin.settings',
 'new_hire',
 'slack_bot',
 'rest_framework',
 'axes',
 'anymail',
 'django_q',
 'crispy_forms',
 'debug_toolbar',
 'rest_framework.authtoken',
 'api']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'organization.middleware.HealthCheckMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'users.middleware.language_middleware',
 'axes.middleware.AxesMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/users/mixins.py", line 27, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "/app/new_hire/views.py", line 40, in get_context_data
    context["overdue_to_do_items"] = ToDoUser.objects.overdue(new_hire)
  File "/app/users/models.py", line 424, in overdue
    .filter(user=user, completed=False, to_do__due_on_day__lt=user.workday)
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 247, in inner
    return func(self._wrapped, *args)
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/app/users/models.py", line 304, in workday
    if start_day > local_day:

Exception Type: TypeError at /new_hire/todos/
Exception Value: '>' not supported between instances of 'NoneType' and 'datetime.date'

Meta:

ACCOUNT_EMAIL | 'admin@example.com'
-- | --
ACCOUNT_PASSWORD | '********************'
AWS_ACCESS_KEY_ID | '********************'
AWS_REGION | 'eu-west-2'
AWS_S3_ENDPOINT_URL | 'https://s3.eu-west-2.amazonaws.com'
AWS_SECRET_ACCESS_KEY | '********************'
AWS_STORAGE_BUCKET_NAME | 'chiefonboardingdemo'
BASE_URL | 'http://0.0.0.0:3000'
CONTENT_LENGTH | ''
CONTENT_TYPE | 'text/plain'
CSRF_COOKIE | 'hvZD30ubyUZljb77BZKSQqKgwXjQTpI7Agm1VvEspzgy7oRKWDHBBya3WYh5SnxE'
DATABASE_URL | 'postgres://postgres:postgres@db:5432/postgres'
DEBUG | 'True'
DEFAULT_FROM_EMAIL | 'Your company onboarding <onboarding@whatever.com>'
DJANGO_SETTINGS_MODULE | 'back.settings'
EMAIL_HOST | 'mail'
EMAIL_PORT | '25'
EMAIL_USE_SSL | 'False'
EMAIL_USE_TLS | 'False'
GATEWAY_INTERFACE | 'CGI/1.1'
GPG_KEY | '********************'
HOME | '/root'
HOSTNAME | '4edc148f466d'
HTTP_ACCEPT | 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8'
HTTP_ACCEPT_ENCODING | 'gzip, deflate, br'
HTTP_ACCEPT_LANGUAGE | 'en-GB,en'
HTTP_CONNECTION | 'keep-alive'
HTTP_COOKIE | ('csrftoken=hvZD30ubyUZljb77BZKSQqKgwXjQTpI7Agm1VvEspzgy7oRKWDHBBya3WYh5SnxE; '  'sessionid=7smd525264shzaqxoh94440xc3bnl9hb')
HTTP_HOST | 'localhost:8000'
HTTP_REFERER | 'http://localhost:8000/new_hire/resources/'
HTTP_SEC_FETCH_DEST | 'document'
HTTP_SEC_FETCH_MODE | 'navigate'
HTTP_SEC_FETCH_SITE | 'same-origin'
HTTP_SEC_FETCH_USER | '?1'
HTTP_SEC_GPC | '1'
HTTP_UPGRADE_INSECURE_REQUESTS | '1'
HTTP_USER_AGENT | ('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, '  'like Gecko) Chrome/106.0.0.0 Safari/537.36')
LANG | 'C.UTF-8'
PATH | '/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
PATH_INFO | '/new_hire/todos/'
PWD | '/app'
PYTHONUNBUFFERED | '1'
PYTHON_GET_PIP_SHA256 | '1e501cf004eac1b7eb1f97266d28f995ae835d30250bec7f8850562703067dc6'
PYTHON_GET_PIP_URL | 'https://github.com/pypa/get-pip/raw/66030fa03382b4914d4c4d0896961a0bdeeeb274/public/get-pip.py'
PYTHON_PIP_VERSION | '22.0.4'
PYTHON_SETUPTOOLS_VERSION | '58.1.0'
PYTHON_VERSION | '3.9.15'
QUERY_STRING | ''
REMOTE_ADDR | '172.23.0.1'
REMOTE_HOST | ''
REQUEST_METHOD | 'GET'
RUN_MAIN | 'true'
SCRIPT_NAME | ''
SECRET_KEY | '********************'
SERVER_NAME | '4edc148f466d'
SERVER_PORT | '8000'
SERVER_PROTOCOL | 'HTTP/1.1'
SERVER_SOFTWARE | 'WSGIServer/0.2'
SHLVL | '0'
SUPERVISOR_ENABLED | '1'
SUPERVISOR_GROUP_NAME | 'devserver'
SUPERVISOR_PROCESS_NAME | 'devserver'
TZ | 'UTC'
_ | '/usr/local/bin/python'
wsgi.errors | <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
wsgi.file_wrapper | <class 'wsgiref.util.FileWrapper'>
wsgi.input | <django.core.handlers.wsgi.LimitedStream object at 0x7f3fa42eec10>
wsgi.multiprocess | False
wsgi.multithread | True
wsgi.run_once | False
wsgi.url_scheme | 'http'
wsgi.version | (1, 0)

Settings:

ABSOLUTE_URL_OVERRIDES | {}
-- | --
ACCOUNT_EMAIL | 'admin@example.com'
ACCOUNT_PASSWORD | '********************'
ADMINS | []
ALLOWED_HOSTS | ['*']
API_ACCESS | '********************'
APPEND_SLASH | True
AUTHENTICATION_BACKENDS | ['axes.backends.AxesBackend', 'django.contrib.auth.backends.ModelBackend']
AUTH_PASSWORD_VALIDATORS | '********************'
AUTH_USER_MODEL | 'users.User'
AWS_ACCESS_KEY_ID | '********************'
AWS_REGION | 'eu-west-2'
AWS_S3_ENDPOINT_URL | 'https://s3.eu-west-2.amazonaws.com'
AWS_SECRET_ACCESS_KEY | '********************'
AWS_STORAGE_BUCKET_NAME | 'chiefonboardingdemo'
AXES_ACCESS_FAILURE_LOG_PER_USER_LIMIT | 1000
AXES_ALLOWED_CORS_ORIGINS | '*'
AXES_CLIENT_STR_CALLABLE | None
AXES_COOLOFF_MESSAGE | 'Account locked: too many login attempts. Please try again later.'
AXES_COOLOFF_TIME | None
AXES_DISABLE_ACCESS_LOG | False
AXES_ENABLED | True
AXES_ENABLE_ACCESS_FAILURE_LOG | False
AXES_ENABLE_ADMIN | True
AXES_FAILURE_LIMIT | 10
AXES_HANDLER | 'axes.handlers.database.AxesDatabaseHandler'
AXES_HTTP_RESPONSE_CODE | 403
AXES_IP_BLACKLIST | None
AXES_IP_WHITELIST | None
AXES_LOCKOUT_CALLABLE | None
AXES_LOCKOUT_TEMPLATE | None
AXES_LOCKOUT_URL | None
AXES_LOCK_OUT_AT_FAILURE | True
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP | False
AXES_LOCK_OUT_BY_USER_OR_IP | False
AXES_META_PRECEDENCE_ORDER | ('REMOTE_ADDR',)
AXES_NEVER_LOCKOUT_GET | False
AXES_NEVER_LOCKOUT_WHITELIST | False
AXES_ONLY_ADMIN_SITE | False
AXES_ONLY_USER_FAILURES | False
AXES_ONLY_WHITELIST | False
AXES_PASSWORD_FORM_FIELD | '********************'
AXES_PERMALOCK_MESSAGE | 'Account locked: too many login attempts. Contact an admin to unlock your account.'
AXES_PROXY_COUNT | None
AXES_PROXY_ORDER | 'left-most'
AXES_PROXY_TRUSTED_IPS | None
AXES_RESET_COOL_OFF_ON_FAILURE_DURING_LOCKOUT | True
AXES_RESET_ON_SUCCESS | False
AXES_SENSITIVE_PARAMETERS | []
AXES_USERNAME_CALLABLE | None
AXES_USERNAME_FORM_FIELD | 'username'
AXES_USE_USER_AGENT | False
AXES_VERBOSE | True
AXES_WHITELIST_CALLABLE | None
BASE_DIR | '/app'
BASE_URL | 'http://0.0.0.0:3000'
CACHES | {'default': {'BACKEND': 'django.core.cache.backends.db.DatabaseCache',              'LOCATION': 'cached_items'}}
CACHE_MIDDLEWARE_ALIAS | 'default'
CACHE_MIDDLEWARE_KEY_PREFIX | '********************'
CACHE_MIDDLEWARE_SECONDS | 600
CORS_ALLOWED_ORIGINS | []
CORS_ALLOW_CREDENTIALS | True
CRISPY_ALLOWED_TEMPLATE_PACKS | 'bootstrap5'
CRISPY_TEMPLATE_PACK | 'bootstrap5'
CSRF_COOKIE_AGE | 31449600
CSRF_COOKIE_DOMAIN | None
CSRF_COOKIE_HTTPONLY | False
CSRF_COOKIE_NAME | 'csrftoken'
CSRF_COOKIE_PATH | '/'
CSRF_COOKIE_SAMESITE | 'Lax'
CSRF_COOKIE_SECURE | False
CSRF_FAILURE_VIEW | 'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME | 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS | []
CSRF_USE_SESSIONS | False
DATABASES | {'default': {'ATOMIC_REQUESTS': False,              'AUTOCOMMIT': True,              'CONN_MAX_AGE': 0,              'ENGINE': 'django.db.backends.postgresql',              'HOST': 'db',              'NAME': 'postgres',              'OPTIONS': {},              'PASSWORD': '********************',              'PORT': 5432,              'TEST': {'CHARSET': None,                       'COLLATION': None,                       'MIGRATE': True,                       'MIRROR': None,                       'NAME': None},              'TIME_ZONE': None,              'USER': 'postgres'}}
DATABASE_ROUTERS | []
DATA_UPLOAD_MAX_MEMORY_SIZE | 2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS | 1000
DATETIME_FORMAT | 'N j, Y, P'
DATETIME_INPUT_FORMATS | ['%Y-%m-%d %H:%M:%S',  '%Y-%m-%d %H:%M:%S.%f',  '%Y-%m-%d %H:%M',  '%m/%d/%Y %H:%M:%S',  '%m/%d/%Y %H:%M:%S.%f',  '%m/%d/%Y %H:%M',  '%m/%d/%y %H:%M:%S',  '%m/%d/%y %H:%M:%S.%f',  '%m/%d/%y %H:%M']
DATE_FORMAT | 'N j, Y'
DATE_INPUT_FORMATS | ['%Y-%m-%d',  '%m/%d/%Y',  '%m/%d/%y',  '%b %d %Y',  '%b %d, %Y',  '%d %b %Y',  '%d %b, %Y',  '%B %d %Y',  '%B %d, %Y',  '%d %B %Y',  '%d %B, %Y']
DEBUG | True
DEBUG_PROPAGATE_EXCEPTIONS | False
DECIMAL_SEPARATOR | '.'
DEFAULT_AUTO_FIELD | 'django.db.models.AutoField'
DEFAULT_CHARSET | 'utf-8'
DEFAULT_EXCEPTION_REPORTER | 'django.views.debug.ExceptionReporter'
DEFAULT_EXCEPTION_REPORTER_FILTER | 'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE | 'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL | 'Your company onboarding <onboarding@whatever.com>'
DEFAULT_HASHING_ALGORITHM | 'sha256'
DEFAULT_INDEX_TABLESPACE | ''
DEFAULT_TABLESPACE | ''
DISALLOWED_USER_AGENTS | []
EMAIL_BACKEND | 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST | 'mail'
EMAIL_HOST_PASSWORD | '********************'
EMAIL_HOST_USER | ''
EMAIL_PORT | 25
EMAIL_SSL_CERTFILE | None
EMAIL_SSL_KEYFILE | '********************'
EMAIL_SUBJECT_PREFIX | '[Django] '
EMAIL_TIMEOUT | None
EMAIL_USE_LOCALTIME | False
EMAIL_USE_SSL | False
EMAIL_USE_TLS | False
FAKE_SLACK_API | '********************'
FILE_UPLOAD_DIRECTORY_PERMISSIONS | None
FILE_UPLOAD_HANDLERS | ['django.core.files.uploadhandler.MemoryFileUploadHandler',  'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE | 2621440
FILE_UPLOAD_PERMISSIONS | 420
FILE_UPLOAD_TEMP_DIR | None
FIRST_DAY_OF_WEEK | 0
FIXTURE_DIRS | ['fixtures']
FORCE_SCRIPT_NAME | None
FORMAT_MODULE_PATH | None
FORM_RENDERER | 'django.forms.renderers.DjangoTemplates'
IGNORABLE_404_URLS | []
INSTALLED_APPS | ['django.contrib.auth',  'django.contrib.contenttypes',  'django.contrib.sessions',  'django.contrib.messages',  'django.contrib.staticfiles',  'django.contrib.humanize',  'users',  'organization',  'user_auth',  'misc',  'back',  'admin.templates',  'admin.notes',  'admin.to_do',  'admin.resources',  'admin.introductions',  'admin.admin_tasks',  'admin.badges',  'admin.integrations',  'admin.preboarding',  'admin.appointments',  'admin.sequences',  'admin.people',  'admin.settings',  'new_hire',  'slack_bot',  'rest_framework',  'axes',  'anymail',  'django_q',  'crispy_forms',  'debug_toolbar',  'rest_framework.authtoken',  'api']
INTERNAL_IPS | ['172.23.0.1', '127.0.0.1', '10.0.2.2']
LANGUAGES | [('en', 'English'),  ('nl', 'Dutch'),  ('fr', 'French'),  ('de', 'German'),  ('tr', 'Turkish'),  ('pt', 'Portuguese'),  ('jp', 'Japanese'),  ('es', 'Spanish')]
LANGUAGES_BIDI | ['he', 'ar', 'ar-dz', 'fa', 'ur']
LANGUAGE_CODE | 'en-us'
LANGUAGE_COOKIE_AGE | None
LANGUAGE_COOKIE_DOMAIN | None
LANGUAGE_COOKIE_HTTPONLY | False
LANGUAGE_COOKIE_NAME | 'django_language'
LANGUAGE_COOKIE_PATH | '/'
LANGUAGE_COOKIE_SAMESITE | None
LANGUAGE_COOKIE_SECURE | False
LANGUAGE_SESSION_KEY | '********************'
LOCALE_PATHS | ('/app/locale',)
LOGGING | {}
LOGGING_CONFIG | 'logging.config.dictConfig'
LOGIN_REDIRECT_URL | 'logged_in_user_redirect'
LOGIN_URL | 'login'
LOGOUT_REDIRECT_URL | 'login'
MANAGERS | []
MEDIA_ROOT | ''
MEDIA_URL | '/'
MESSAGE_STORAGE | 'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE | ['corsheaders.middleware.CorsMiddleware',  'django.middleware.security.SecurityMiddleware',  'whitenoise.middleware.WhiteNoiseMiddleware',  'django.contrib.sessions.middleware.SessionMiddleware',  'django.middleware.locale.LocaleMiddleware',  'organization.middleware.HealthCheckMiddleware',  'django.middleware.common.CommonMiddleware',  'django.middleware.csrf.CsrfViewMiddleware',  'django.contrib.auth.middleware.AuthenticationMiddleware',  'django.contrib.messages.middleware.MessageMiddleware',  'django.middleware.clickjacking.XFrameOptionsMiddleware',  'users.middleware.language_middleware',  'axes.middleware.AxesMiddleware',  'debug_toolbar.middleware.DebugToolbarMiddleware']
MIGRATION_MODULES | {}
MONTH_DAY_FORMAT | 'F j'
NUMBER_GROUPING | 0
OLD_PASSWORD_FIELD_ENABLED | '********************'
PASSWORD_HASHERS | '********************'
PASSWORD_RESET_TIMEOUT | '********************'
PASSWORD_RESET_TIMEOUT_DAYS | '********************'
PREPEND_WWW | False
Q_CLUSTER | {'bulk': 10,  'catch_up': False,  'max_attempts': 2,  'name': 'DjangORM',  'orm': 'default',  'queue_limit': 50,  'retry': 1800,  'timeout': 90,  'workers': 1}
REST_FRAMEWORK | {'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.TokenAuthentication'],  'DEFAULT_PERMISSION_CLASSES': ['api.permissions.AdminPermission'],  'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer']}
REST_FRAMEWORK_ACTIVE | True
ROOT_URLCONF | 'back.urls'
RUNNING_TESTS | False
SECRET_KEY | '********************'
SECURE_BROWSER_XSS_FILTER | False
SECURE_CONTENT_TYPE_NOSNIFF | True
SECURE_HSTS_INCLUDE_SUBDOMAINS | False
SECURE_HSTS_PRELOAD | False
SECURE_HSTS_SECONDS | 0
SECURE_PROXY_SSL_HEADER | None
SECURE_REDIRECT_EXEMPT | []
SECURE_REFERRER_POLICY | 'same-origin'
SECURE_SSL_HOST | None
SECURE_SSL_REDIRECT | False
SERVER_EMAIL | 'root@localhost'
SESSION_CACHE_ALIAS | 'default'
SESSION_COOKIE_AGE | 1209600
SESSION_COOKIE_DOMAIN | None
SESSION_COOKIE_HTTPONLY | True
SESSION_COOKIE_NAME | 'sessionid'
SESSION_COOKIE_PATH | '/'
SESSION_COOKIE_SAMESITE | 'Lax'
SESSION_COOKIE_SECURE | False
SESSION_ENGINE | 'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE | False
SESSION_FILE_PATH | None
SESSION_SAVE_EVERY_REQUEST | False
SESSION_SERIALIZER | 'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE | 'back.settings'
SHORT_DATETIME_FORMAT | 'm/d/Y P'
SHORT_DATE_FORMAT | 'm/d/Y'
SIGNING_BACKEND | 'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS | []
SITE_ROOT | '/app'
SLACK_APP_TOKEN | '********************'
SLACK_BOT_TOKEN | '********************'
SLACK_USE_SOCKET | False
STATICFILES_DIRS | ['/app/static']
STATICFILES_FINDERS | ['django.contrib.staticfiles.finders.FileSystemFinder',  'django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATICFILES_STORAGE | 'whitenoise.storage.CompressedStaticFilesStorage'
STATIC_ROOT | '/app/staticfiles'
STATIC_URL | '/static/'
TEMPLATES | [{'APP_DIRS': True,   'BACKEND': 'django.template.backends.django.DjangoTemplates',   'DIRS': [],   'OPTIONS': {'context_processors': ['django.template.context_processors.debug',                                      'django.template.context_processors.request',                                      'django.contrib.auth.context_processors.auth',                                      'django.contrib.messages.context_processors.messages',                                      'organization.context_processor.org_include']}}]
TEMPLATE_DIRS | ('/app/templates',)
TEST_NON_SERIALIZED_APPS | []
TEST_RUNNER | 'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR | ','
TIME_FORMAT | 'P'
TIME_INPUT_FORMATS | ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
TIME_ZONE | 'UTC'
TWILIO_ACCOUNT_SID | ''
TWILIO_AUTH_TOKEN | '********************'
TWILIO_FROM_NUMBER | ''
USE_I18N | True
USE_L10N | True
USE_THOUSAND_SEPARATOR | False
USE_TZ | True
USE_X_FORWARDED_HOST | False
USE_X_FORWARDED_PORT | False
WSGI_APPLICATION | 'back.wsgi.application'
X_FRAME_OPTIONS | 'DENY'
YEAR_MONTH_FORMAT | 'F Y'

**Comment by GDay** [comment]
Thanks for the detailed report! 

Looks like the user that you assigned the task for isn't a manager or admin. That's the issue here. Normal users get only access to the same dashboard as new hires get.

I will fix this later this week by:
1. Restricting who you can assign to an admin task (must be admin or manager)
2. Add a check for when `None` is set as the `start_date` so it won't cause issues in the future.

**Comment by GDay** [comment]
Will be fixed when I merge #256

**Comment by GDay** [comment]
Apologies for the delay. This got fixed now!

Thanks again for reporting the issue.
